[build]
publish = "dist"
command = "corepack enable && pnpm install --store=node_modules/.pnpm-store && pnpm run build"

[build.environment]
# 使用 LTS 版本，确保依赖（如 @vue-macros 系列）在 Netlify 上稳定安装
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
